version: '3'
services:
  db:
    image: postgres:14.1-alpine
    container_name: chriscodetestDB
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chriscodetest
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  app:
    image: chriscodetest
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/chriscodetest
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  db:
    driver: local
