version: '3'
services:
  app:
    image: christest-docker
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
