version: '3'
services:
  app:
    image: chriscodetest
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
  db:
    image: postgres:14.1-alpine
    restart: always
    enviroment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
